name: "test"
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          npm ci
      - name: build
        run: |
          npm run build
          npm run package
      - name: test
        run: |
          npm test

  check-permission:
    name: check permission
    runs-on: ubuntu-latest
    outputs:
      permission: ${{ steps.check.outputs.permission }}
    steps:
      - id: check
        uses: shogo82148/actions-check-permissions@v1

  integrated:
    name: integrated test
    runs-on: ubuntu-latest
    needs:
      - check-permission
    if: needs.check-permission.outputs.permission == 'write'
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          npm ci
      - name: build
        run: |
          npm run build
          npm run package

      - name: Create Release
        id: create_release
        uses: ./
        with:
          tag_name: test-${{ github.run_id }}
          release_name: Test for ${{ github.run_id }}
          draft: true
          prerelease: true
          body: |
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: cleanup
        run: |
          curl -XDELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}
        if: always()
        env:
          GITHUB_TOKEN: ${{ github.token }}
